- name: OS-specific tasks
  include_tasks: "{{ ansible_distribution|lower }}.yml"

- name: pyenv tasks
  include_tasks: pyenv.yml
  when: python3_pyenv != None

- name: add local Python path to login file
  become: true
  lineinfile:
    line: "export PATH={{ python3_local }}:$PATH"
    path: "{{ python3_bashrc }}"
    create: true
    state: present
