## Tasks unique to Ubuntu.
##
- name: install Python utility packages
  become: true
  apt:
    name:
      - python3-pip
      - python3-virtualenv
      - python3-dev
      - virtualenv
  when: python3_pyenv == None


- name: requirements for pyenv install
  block:
    - name: install system packages required for pyenv
      apt:
        name:
          - curl
          - gcc
          - git
          - libbz2-dev
          - libreadline-dev
          - libssl-dev
          - libsqlite3-dev
          - make
          - zlib1g-dev
        state: present
  become: true
  when: python3_pyenv != None
