## Tasks for the tmpdir role.
##
- debug:
    var: tmpdir_root
    verbosity: 2

- debug:
    var: tmpdir_template
    verbosity: 2

- name: create temporary directory
  block:
    - name: create temporary
      tempfile:
        state: directory
      register: tmpdir_tempfile
      notify:
        - tmpdir remove
    - name: set tmpdir_path
      set_fact:
        tmpdir_path: "{{ tmpdir_tempfile.path }}"
  when: not tmpdir_path

- debug:
    var: tmpdir_path
    verbosity: 2
